services:
  postgres:
    container_name: immogest-backend-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
      POSTGRES_DB: ${DATABASE_NAME:-immogest}
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forum-network

volumes:
  postgres_data:

networks:
  forum-network:
    driver: bridge