export enum PropertyTaxRegime {
  // Pinel
  PINEL_6_YEARS = 'PINEL_6_YEARS',
  PINEL_9_YEARS = 'PINEL_9_YEARS',
  PINEL_REHABILITATION = 'PINEL_REHABILITATION',

  // Revenus fonciers
  CLASSIC_REAL_ESTATE_INCOME = 'CLASSIC_REAL_ESTATE_INCOME',
  CLASSIC_MICRO_REAL_ESTATE_INCOME = 'CLASSIC_MICRO_REAL_ESTATE_INCOME',

  // BIC
  BIC_REAL = 'BIC_REAL',
  BIC_MICRO = 'BIC_MICRO',

  // Besson
  BESSON_NEW = 'BESSON_NEW',
  BESSON_OLD = 'BESSON_OLD',
  BESSON_REHABILITATED = 'BESSON_REHABILITATED',

  // Robien
  ROBIEN_NEW = 'ROBIEN_NEW',
  ROBIEN_RECENTERED = 'ROBIEN_RECENTERED',
  ROBIEN_RECENTERED_REHABILITATED = 'ROBIEN_RECENTERED_REHABILITATED',

  // Borloo
  BORLOO_NEW = 'BORLOO_NEW',
  BORLOO_OLD = 'BORLOO_OLD',
  BORLOO_REHABILITATED = 'BORLOO_REHABILITATED',

  // Scellier
  SCELLIER = 'SCELLIER',
  SCELLIER_INTERMEDIATE = 'SCELLIER_INTERMEDIATE',
  SCELLIER_REHABILITATION = 'SCELLIER_REHABILITATION',

  // Duflot
  DUFLOT_NEW = 'DUFLOT_NEW',
  DUFLOT_REHABILITATION = 'DUFLOT_REHABILITATION',

  // Autres dispositifs spécifiques
  CENSI_BOUVARD = 'CENSI_BOUVARD',
  HISTORICAL_MONUMENT = 'HISTORICAL_MONUMENT',
  MALRAUX = 'MALRAUX',
  GIRARDIN = 'GIRARDIN',
  GIRARDIN_INTERMEDIATE = 'GIRARDIN_INTERMEDIATE',
  PAUL = 'PAUL',
  PAUL_INTERMEDIATE = 'PAUL_INTERMEDIATE',
  DISMEMBERMENT = 'DISMEMBERMENT',
  DEMESSINE = 'DEMESSINE',
  ZRR = 'ZRR',
  PERISSOL = 'PERISSOL',
  DENORMANDIE = 'DENORMANDIE',

  // Formes sociétaires
  SCI_IS = 'SCI_IS',
  SCI_IR = 'SCI_IR',
  SARL = 'SARL',
  FAMILY_SARL = 'FAMILY_SARL',
  SAS = 'SAS',
  OTHER_COMPANY = 'OTHER_COMPANY',

  // Autres
  UNDEFINED = 'UNDEFINED',
  OTHER = 'OTHER'
} 