export enum DocumentType {
  // Contrats
  LEGAL_INSURANCE = 'LEGAL_INSURANCE',
  OWNER_INSURANCE = 'OWNER_INSURANCE',
  BOILER_MAINTENANCE_CONTRACT = 'BOILER_MAINTENANCE_CONTRACT',
  WATER_CONTRACT = 'WATER_CONTRACT',
  ELECTRICITY_CONTRACT = 'ELECTRICITY_CONTRACT',
  GAS_CONTRACT = 'GAS_CONTRACT',
  INTERNET_CONTRACT = 'INTERNET_CONTRACT',
  PHONE_CONTRACT = 'PHONE_CONTRACT',

  // Diagnostics
  SANITATION_DIAGNOSIS = 'SANITATION_DIAGNOSIS',
  ELECTRICITY_DIAGNOSIS = 'ELECTRICITY_DIAGNOSIS',
  GAS_DIAGNOSIS = 'GAS_DIAGNOSIS',
  CARREZ_LAW_DIAGNOSIS = 'CARREZ_LAW_DIAGNOSIS',
  ENERGY_PERFORMANCE_DIAGNOSIS = 'ENERGY_PERFORMANCE_DIAGNOSIS',
  LEAD_DIAGNOSIS = 'LEAD_DIAGNOSIS',
  LIVING_SPACE_DIAGNOSIS = 'LIVING_SPACE_DIAGNOSIS',
  TERMITE_DIAGNOSIS = 'TERMITE_DIAGNOSIS',
  ASBESTOS_DIAGNOSIS = 'ASBESTOS_DIAGNOSIS',
  RISK_POLLUTION_STATEMENT = 'RISK_POLLUTION_STATEMENT',
  NOISE_EXPOSURE_PLAN = 'NOISE_EXPOSURE_PLAN',
  FIRE_RISK = 'FIRE_RISK',
  FIRE_ALARM_CHECK = 'FIRE_ALARM_CHECK'
} 